### ISSUE TITLE
Live2DForScala API

### ISSUE THREAD

**Issue by JackCloudman** [brianhsu/Live2DForScala#1]
Hello! I'm currently working on a project that involves integrating an LLM (ChatGPT) with a virtual avatar. I've been exploring your work, and I must say, it's truly impressive.

To make this integration successful, I'd like to control your virtual avatar using an API from a language other than Scala, as I'm not familiar with it. While I'm planning to attempt this implementation myself, I think I could use some guidance. :pray:

**Comment by JackCloudman** [comment]
Okay with a bit help of GPT-4 I did this.
https://github.com/brianhsu/Live2DForScala/assets/17970185/09354b43-f2cf-4a84-93de-88f648b48ea7

**Comment by brianhsu** [comment]
Seems you already figure out how to do that. Glade to hear that. 
Feel free to ask any further question if you need.
