### ISSUE TITLE
通過JOGL打開部分live2d,會出現異常：IndexOutOfBoundsException: Required 1 remaining elements in buffer, only had 0

### ISSUE THREAD

**Issue by leck995** [brianhsu/Live2DForScala#3]
您好，因為之前瞭解到可以使用中文進行對話，我將優先使用中文，如果有困擾，可以告知我。
通過jogl渲染時，部分live2d無法正常顯示，會無限報錯IndexOutOfBoundsException
在您提供的example中swing+jogl 进行运行也會有同樣的問題，而通過swt+jwjgl可以成功運行該live2d。
我將造成該異常的live2d打包上傳到了onedrive,以便您進行參考，鏈接： [https://1drv.ms/u/s!AoUJInmLIR3yjRPHA_UT3k-wEuO2?e=jpHHdy](https://1drv.ms/u/s!AoUJInmLIR3yjRPHA_UT3k-wEuO2?e=jpHHdy)
具體報錯如下
![BUG](https://github.com/brianhsu/Live2DForScala/assets/46077555/19de7522-7365-4a9b-a6eb-8e9ec01d8184)

另外，在您提供的example中，swing+jogl也有一個小BUG，在無camera的計算機上無法運行，這與涉及面部捕捉的UI有關。

**Comment by brianhsu** [comment]
好的，謝謝，我有空的時候再研究一下看能不能修正。

不過 OpenGL 不是我的領域，當初我只是單純 porting 原本 Live2D Native SDK 給的範例，不一定能夠解決。XD

**Comment by brianhsu** [comment]
Hi, please update to v2.0.2 and verify if this issue has been resolved. Thanks.

**Comment by leck995** [comment]
是的，感謝辛苦修複。
